from pathlib import Path

import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset

from .kinematics import DifferentiableUR3FK, rotmat_to_quat


JOINT_NAMES = ["base", "shoulder", "elbow", "wrist1", "wrist2", "wrist3"]


def build_dataset_columns() -> list[str]:
	pos_cols = ["x", "y", "z"]
	quat_cols = ["qw", "qx", "qy", "qz"]
	sin_cols = [f"sin_{j}" for j in JOINT_NAMES]
	cos_cols = [f"cos_{j}" for j in JOINT_NAMES]
	return pos_cols + quat_cols + sin_cols + cos_cols


def _sample_q_uniform(num_samples: int, q_min: np.ndarray, q_max: np.ndarray, rng: np.random.Generator) -> np.ndarray:
	return rng.uniform(low=q_min, high=q_max, size=(num_samples, 6)).astype(np.float32)


def generate_fk_dataset_csv(
	output_path: str | Path,
	num_samples: int,
	chunk_size: int = 100_000,
	seed: int = 42,
	q_min: np.ndarray | None = None,
	q_max: np.ndarray | None = None,
) -> Path:
	"""Generate FK training dataset using the project's differentiable UR3 FK model."""
	if num_samples <= 0:
		raise ValueError("num_samples must be > 0")
	if chunk_size <= 0:
		raise ValueError("chunk_size must be > 0")

	q_min = np.asarray(q_min if q_min is not None else [-np.pi] * 6, dtype=np.float32)
	q_max = np.asarray(q_max if q_max is not None else [np.pi] * 6, dtype=np.float32)
	if q_min.shape != (6,) or q_max.shape != (6,):
		raise ValueError("q_min and q_max must both be length-6 arrays.")

	output_path = Path(output_path)
	output_path.parent.mkdir(parents=True, exist_ok=True)

	fk = DifferentiableUR3FK().eval()
	rng = np.random.default_rng(seed)
	columns = build_dataset_columns()

	if output_path.exists():
		output_path.unlink()

	remaining = num_samples
	wrote_header = False

	with torch.no_grad():
		while remaining > 0:
			n = min(chunk_size, remaining)
			q_np = _sample_q_uniform(n, q_min=q_min, q_max=q_max, rng=rng)
			q = torch.from_numpy(q_np)

			pos, rot = fk(q)
			quat = rotmat_to_quat(rot)

			sin_q = torch.sin(q)
			cos_q = torch.cos(q)
			row_tensor = torch.cat([pos, quat, sin_q, cos_q], dim=1)

			df = pd.DataFrame(row_tensor.cpu().numpy(), columns=columns)
			df.to_csv(output_path, index=False, mode="a", header=not wrote_header)

			wrote_header = True
			remaining -= n

	return output_path

# Dataset class for UR3 IK solving

class UR3IKDataset(Dataset):
    """PyTorch Dataset for UR3 IK solving, loading from a CSV generated by generate_fk_dataset_csv."""

    def __init__(self, csv_path: str | Path):
        df = pd.read_csv(csv_path)
        sin_cos_cols = [f"sin_{j}" for j in JOINT_NAMES] + [f"cos_{j}" for j in JOINT_NAMES]
        self.joints = torch.tensor(df[sin_cos_cols].values, dtype=torch.float32)
        self.poses = torch.tensor(df[["x", "y", "z", "qw", "qx", "qy", "qz"]].values, dtype=torch.float32)

    def __len__(self) -> int:
        return len(self.poses)

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor]:
        return self.joints[idx], self.poses[idx]